stages:
  image_extraction:
    cmd: python src/humanActivityRecognition/pipeline/stage_01_image_extraction.py
    deps:
      - src/humanActivityRecognition/pipeline/stage_01_image_extraction.py
      - data/videoDataset
      - config/config.yaml
      - params.yaml
    params:
      - MAX_WORKERS
      - IMAGE_HEIGHT
      - IMAGE_WIDTH
      - SEQUENCE_LENGTH
    outs:
      - data/imageDataset

  keypoint_detection:
    cmd: python src/humanActivityRecognition/pipeline/stage_02_keypoint_detection.py
    deps:
      - src/humanActivityRecognition/pipeline/stage_02_keypoint_detection.py
      - data/imageDataset
      - config/config.yaml
    outs:
      - data/keypointDataset
      - data/boxDataset

  bluring_image:
    cmd: python src/humanActivityRecognition/pipeline/stage_03_bluring_image.py
    deps:
      - src/humanActivityRecognition/pipeline/stage_03_bluring_image.py
      - data/imageDataset
      - data/boxDataset
      - config/config.yaml
    params:
      - BLUR_STRENGTH
    outs:
      - data/bluredImageDataset

  spliting_dataset:
    cmd: python src/humanActivityRecognition/pipeline/stage_04_spliting_dataset.py
    deps:
      - src/humanActivityRecognition/pipeline/stage_04_spliting_dataset.py
      - data/bluredImageDataset
      - data/keypointDataset
      - config/config.yaml
    params:
      - TRAIN_RATION
      - SEED
    outs:
      - data/splitDataset/keypointDataset
      - data/splitDataset/bluredImageDataset

  data_augmentation:
    cmd: python src/humanActivityRecognition/pipeline/stage_05_data_augmentation.py
    deps:
      - src/humanActivityRecognition/pipeline/stage_05_data_augmentation.py
      - data/splitDataset/keypointDataset
      - data/splitDataset/bluredImageDataset
      - config/config.yaml
    params:
      - ROTATE_FACTORS
      - SCALE_FACTORS
      - FLIP_FACTOR
      - MAX_WORKERS
    outs:
      - data/augmentedDataset/bluredImageDataset
      - data/augmentedDataset/keypointDataset

  feature_extraction:
    cmd: python src/humanActivityRecognition/pipeline/stage_06_feature_extraction.py
    deps:
      - src/humanActivityRecognition/pipeline/stage_06_feature_extraction.py
      - data/augmentedDataset/bluredImageDataset
      - config/config.yaml
    params:
      - IMAGE_HEIGHT
      - IMAGE_WIDTH
    outs:
      - data/featureDataset/bluredImageDataset

  final_dataset:
    cmd: python src/humanActivityRecognition/pipeline/stage_07_final_dataset.py
    deps:
      - src/humanActivityRecognition/pipeline/stage_07_final_dataset.py
      - data/featureDataset/bluredImageDataset
      - data/augmentedDataset/keypointDataset
      - config/config.yaml
    params:
      - IMAGE_HEIGHT
      - IMAGE_WIDTH
      - MAX_WORKERS
    outs:
      - data/finalDataset/bluredImageDataset
      - data/finalDataset/keypointDataset


