# paarallelism
MAX_WORKERS: 4

# Data
IMAGE_HEIGHT: 128
IMAGE_WIDTH: 128
SEQUENCE_LENGTH: 20

# Bluring
BLUR_STRENGTH: 60

# split ratio
TRAIN_RATION: 0.8
SEED: 42

# augmentation
ROTATE_FACTORS: [30,-30,20,-20,10,-10]
SCALE_FACTORS: [1.1,1.2,1.3,0.9,0.8,0.7]
FLIP_FACTOR: true