artifacts_root: data


image_extraction:
  root_dir: data
  source_dir: data/videoDataset
  destination_dir: data/imageDataset
  image_format: jpg

keypoint_detection:
  root_dir: data
  image_dir: data/imageDataset
  keypoint_dir: data/keypointDataset
  box_dir: data/boxDataset
  yolo_model_path: data/model/yolo11n-pose.pt
  image_format: jpg
  keypoint_format: npy

bluring_image:
  root_dir: data
  image_dir: data/imageDataset
  box_dir: data/boxDataset
  blured_image_dir: data/bluredImageDataset
  image_format: jpg
  box_format: npy

spliting_dataset:
  blured_image_dir: data/bluredImageDataset
  keypoint_dir: data/keypointDataset
  keypoint_split_dir: data/splitDataset/keypointDataset
  blured_split_dir: data/splitDataset/bluredImageDataset
  split_dir_dict_path: data/splitDataset/split_dir_dict.npy

data_augmentation:
  keypoint_split_dir: data/splitDataset/keypointDataset
  keypoint_aug_dir: data/augmentedDataset/keypointDataset
  blured_split_dir: data/splitDataset/bluredImageDataset
  blured_aug_dir: data/augmentedDataset/bluredImageDataset

feature_extraction:
  model_weights: imagenet
  blured_aug_dir: data/augmentedDataset/bluredImageDataset
  blured_feature_dir: data/featureDataset/bluredImageDataset
  feature_format: npy
  image_format: jpg

final_dataset:
  blured_feature_dir: data/featureDataset/bluredImageDataset
  keypoint_aug_dir: data/augmentedDataset/keypointDataset
  blured_final_dir: data/finalDataset/bluredImageDataset
  keypoint_final_dir: data/finalDataset/keypointDataset
  data_format: npy

prepare_base_model:
  root_dir: data/model
  base_model_path: data/model/base_model.keras
  model_architecture_plot_path: data/results/base_model_architecture.png
  blured_final_dir: data/finalDataset/bluredImageDataset
  keypoint_final_dir: data/finalDataset/keypointDataset

prepare_callbacks:
  root_dir: data/results
  best_checkpoint_path: data/results/model_checkpoint/model_best/best_model.keras
  checkpoint_path: data/results/model_checkpoint/models
  history_path: data/results/model_checkpoint/history.txt

